name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ "main" ]   # mainブランチにpushされたら実行
  workflow_dispatch:       # 手動実行も可能に

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: GitHub Pages にデプロイ
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # リポジトリ直下を公開
