name: Deploy to Xserver

on:
  push:
    branches:
      - main   # mainブランチにpushされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Xserver via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.XSERVER_HOST }}
          username: ${{ secrets.XSERVER_USER }}
          password: ${{ secrets.XSERVER_PASS }}
          server-dir: /home/xs671474/xs671474.xsrv.jp/public_html/
          local-dir: ./  # 必要なら dist/ や build/ に変更
